{{- if .Values.funny_ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: funny-ingress
spec:
  rules:
    - host: maxim-projects.com
      http:
        paths:
          - path: /funnyfact
            pathType: Prefix
            backend:
              service:
                name: funnyfact-webapp
                port:
                  number: 80
  {{- end }}
