{{- if .Values.useless_ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: useless-ingress
spec:
  rules:
    - host: maxim-projects.com
      http:
        paths:
          - path: /uselessfact
            pathType: Prefix
            backend:
              service:
                name: uselessfact-webapp
                port:
                  number: 80
  {{- end }}
