replicaCount: 1
image:
  repository: 567376135918.dkr.ecr.eu-central-1.amazonaws.com/url-consumer-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 80
  type: ClusterIP
environment:
  API_URL: "https://api.chucknorris.io/"
ingress:
  enabled: true
funny_ingress:
  enabled: true
useless_ingress:
  enabled: false
serviceAccount:
  create: false
