name: Build and push image for desired service

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name'     
        required: true

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd ./url-consumer-app
        docker build -t url-consumer-app-test . 
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
        local-image: url-consumer-app-test
        image: url-consumer-app-test:${{ github.sha }}
        
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update the relevant helm chart
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_NAME }}
        cd ./url-consumer-app
        helm install ${{ github.event.inputs.service }} ./webapp --values ./webapp/values-${{ github.event.inputs.service }}.yaml
