name: Build image for desired service

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd ./url-consumer-app
        docker build -t url-consumer-app-test . 
        docker tag url-consumer-app-test:latest 567376135918.dkr.ecr.eu-central-1.amazonaws.com/url-consumer-app:latest
